version: '3.3'

services:
  db:
    image: wealth-auth-db:latest
    container_name: wealth-auth-db
    volumes:
      - ./var/postgres/datadir:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=dabbedabbu

  redis:
    image: wealth-auth-redis:latest
    container_name: wealth-auth-redis
    ports:
      - "6379:6379"